### ISSUE TITLE
Crashing when eating

### ISSUE THREAD

**Issue by Oddellis** [squeek502/AppleCore#139] opened 2019-05-11 01:18 UTC
[crash-2019-05-11_01.55.09-client.txt](https://github.com/squeek502/AppleCore/files/3168461/crash-2019-05-11_01.55.09-client.txt)

      I have the issue that when I attempt to eat something in a world (any world, but I tend to use Biomes O'Plenty a lot) the game crashes and the ensuing message is that Applecore is the issue. I know that somebody has brought this up before, but I have never tried the mod that they used.

      This has happened about 40 times in total across many different modpacks and it happens every time I install my favourite mods (although I don't remember which at the moment).

      I have attached the crash report file, but if anyone needs anything else, please say. I am just getting so annoyed by Applecore at this point! Any pointers?

**Comment by squeek502** [comment] 2019-05-11 01:48
Update CplPibald's Tweaks to >= v1.1.1.

Duplicate of https://github.com/squeek502/AppleCore/issues/137 and https://github.com/squeek502/AppleCore/issues/136 and  https://github.com/squeek502/AppleCore/issues/135 and https://github.com/squeek502/AppleCore/issues/134.

**Closed as completed by squeek502** 2019-05-11 01:48 UTC
Labels: duplicate, mod compat
