### ISSUE TITLE
Incompatibility with Fastcraft

### ISSUE THREAD

**Issue by Sunconure11** [squeek502/AppleCore#18] opened 2015-04-02 21:14 UTC
There appears to be some kind of issue with running this mod on the serverside with Fastcraft.

http://pastebin.com/hvpd76qq

**Comment by squeek502** [comment] 2015-04-03 00:01
Looks like a duplicate of #17.

**Comment by sfPlayer1** [comment] 2015-04-03 01:57
It's crashing inside the AppleCore transformer, which is always its own fault since it's covered by the asm transformer exclusion. With issue #19 fixed that'd be impossible.

**Comment by ultrasn0w** [comment] 2015-04-12 02:50
Am I understanding rhis correctly that the incompatibility can be fixed but simply hasn't yet?
Or Is this a general compatibility Issue?

**Comment by chrisk123999** [comment] 2015-04-14 04:58
Looking at the crash log there is also ForgeEssentials in their as well.  I currently have a server working fine with AppleCore and Fastcraft both added.  However adding ForgeEssentials gets me the same crash as the one above.

**Comment by PitchBright** [comment] 2015-08-05 08:53
Fastcraft 1.21 is said to be incompatible with ForgeEssentials, FWIW.

**Comment by squeek502** [comment] 2015-12-21 05:46
This should be fixed as of the latest commits I think. If anyone wants to help test it and confirm/deny, download the latest build here: https://drone.io/github.com/squeek502/AppleCore/files

**Comment by squeek502** [comment] 2016-01-25 22:44
Closing. Re-open if 1.3.0 is incompatible with FastCraft.

**Closed by squeek502** 2016-01-25 22:44 UTC
