### ISSUE TITLE
minecraft Server Crash

### ISSUE THREAD

**Issue by geomead** [squeek502/AppleCore#51] opened 2016-03-20 23:40 UTC
Building my own server, I think AppleCore is causing the issue, can you advise?

http://pastebin.com/04rTjjFm

**Comment by squeek502** [comment] 2016-03-21 19:09
If you remove AppleCore (and The Spice of Life), does the crash go away?

**Comment by chanzie** [comment] 2016-04-07 14:26
on mine its hunger overhaul and apple core and yes the crash goes away

**Comment by squeek502** [comment] 2016-04-07 16:19
@chanzie can you post your crash log please?

**Comment by chanzie** [comment] 2016-04-08 05:46
http://pastebin.com/d137Xsmt
applecore null.pointerexceeption is found on line 302ish

**Comment by squeek502** [comment] 2016-04-08 06:30
That seems to be an unrelated warning from [an OpenModsLib sanity check](https://github.com/OpenMods/OpenModsLib/blob/master/src/main/java/openmods/injector/InjectorSanityChecker.java). Not sure how the actual crash in the log could be related to AppleCore.

When is your crash occurring?

**Comment by TheOnlySilverClaw** [comment] 2016-04-23 16:36
I can confirm we have a similar error when loading AppleCore with the latest Forge version. Using recommended or removing AppleCore solves the problem.

**Comment by chanzie** [comment] 2016-04-24 00:28
that crash was occurring about midway though startup of mc itself if I am remembering correctly and both of what silverclaw said was my two fixes for it I rolled it back to 1.1 and it did work fine but the 1.3 for the most recent forge just implodes launch

**Comment by squeek502** [comment] 2016-05-03 04:51
Try v1.3.1: https://github.com/squeek502/AppleCore/releases/tag/v1.3.1

**Comment by mcgraj3** [comment] 2016-05-24 23:07
Getting this crash on v1.3.1. I have tried other versions to no avail, pulling AppleCore and other mods that require the dependency solves the problem. Pastebin below includes my mods and dependencies at the top...

http://pastebin.com/Qyc6Es80

**Comment by squeek502** [comment] 2016-05-24 23:20
@mcgraj3, currently AppleCore is incompatible with sprinkles_for_vanilla. Unfortunately you'll have to remove either AppleCore or sprinkles_for_vanilla.

**Comment by mcgraj3** [comment] 2016-05-24 23:43
@squeek502: I only use it to prevent forest fires and Enderman griefing, so I will see if I can find another solution as I really want to use AppleCore. Thanks for the help!

**Comment by squeek502** [comment] 2016-06-09 19:35
All of these crashes are different from one another and all might be resolved at this point:
- @geomead's crash doesn't seem to be related to AppleCore, it is a false positive fixed by 9ee4d897c930fe0b991e06f1f1503772302e506e
- @chanzie's crash also seems to be an unrelated false positive fixed by 9ee4d897c930fe0b991e06f1f1503772302e506e
- sprinkles_for_vanilla compatibility fixed by 5c9cf24cb4d45c5ac7e9145e12fca2c1ec29ed18

Closing this issue. If any of you are still experiencing these crashes with AppleCore 1.3.2, please open a new issue.

**Closed as completed by squeek502** 2016-06-09 19:35 UTC
Labels: bug
