### ISSUE TITLE
Minimal File Issue

### ISSUE THREAD

**Issue by BraniyaKz** [squeek502/AppleCore#131] opened 2019-01-26 10:47 UTC
## This has been happening for a great many mods in the log, and I don't know why.

**Minecraft Version:** 1.12.2
**Minecraft Forge Version:** 14.23.5.2808
**Apple Core Version:** 3.1.4

> [05:10:45] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in [1.12.2] AppleCore by squeek502 (3.1.4).jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [05:10:45] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!

### _What is this, anyway?_

**Comment by squeek502** [comment] 2019-01-26 13:28
Duplicate of #122

**Closed as completed by squeek502** 2019-01-26 13:28 UTC
