### ISSUE TITLE
crashes whenever i eat something

### ISSUE THREAD

**Issue by Apocolyptik** [squeek502/AppleCore#123] opened 2018-06-09 06:53 UTC
[crash log](https://paste.dimdev.org/ujoyuqupip.mccrash)

i can't decide if it's a Spice of Life: Carrot Edition problem or an Applecore problem so i figured i would start here
unfortunately it's also possible that some other mod is conflicting as i do have a somewhat large mod list.

**Comment by squeek502** [comment] 2018-06-09 10:14
Seems likely that this is a mod conflict issue. Judging from TSoL:Carrot source code, the error is caused by [`event.player` being null here](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/master-1.11.2/src/main/java/com/cazsius/solcarrot/handler/HandlerFoodTracker.java#L18), which really shouldn't be possible. My guess is some other mod is somehow interfering with the FoodStats modifications of AppleCore (skipping/modifying the modified constructor of FoodStats within EntityPlayer init? Overwriting FoodStats entirely?).

If you could try narrowing down the potential conflicting mods, that'd help a lot.

**Comment by Apocolyptik** [comment] 2018-06-10 04:47
i've narrowed it down to these mods, they're the only new ones i've added to the bundle that i play with
(i also have the latest version of Cyclic but i tried taking it out to see if it affected anything and nothing changed)

HammerCore 1.12.2-1.9.9.11
randomtweaks-1.12.2-2.0.0.1
BaseMetals-1.12-2.5.0-beta5.214
ModernMetals-1.12-2.5.0-beta5.120
NetherMetals-1.12-1.2.0-beta3.52
OreSpawn-1.12-3.3.0.136
mysticalagriculture-1.12-1.6.10
cucumber-1.12-1.1.0
moartinkers-0.5.4
weaponlevels-2.5.0
armoryexpansion-0.1.1a
CookingForBlockheads_1.12.2-6.4.39

i crash whenever i eat anything btw, whether it's a vanilla Minecraft steak or a modded food item like Cyclic's inventory crafting table cake.... thingy

**Comment by squeek502** [comment] 2018-06-10 05:09
Great, thanks. Will try to reproduce it and see what's going on.

**Comment by Apocolyptik** [comment] 2018-06-11 06:17
interesting, i removed Spice of Life: Carrot Edition and my game stopped crashing whenever i tried to eat something. should i poke the creator of that mod and let them know what's going on as well??

**Comment by squeek502** [comment] 2018-06-11 06:36
I believe it's a conflict between AppleCore and RandomTweaks, as RandomTweaks [overloads FoodStats](https://github.com/TheRandomLabs/RandomTweaks/blob/1.12.2/src/main/java/com/therandomlabs/randomtweaks/common/RTFoodStats.java), which would cause this error. It's not related to Spice of Life: Carrot Edition.

I'll make an issue on Random Tweaks' issue tracker with suggestions about how to fix this in a bit.

**Comment by Apocolyptik** [comment] 2018-06-11 08:19
ohhh, alrighty! i guess this can be closed now? :D thanks for looking into this!!

**Comment by squeek502** [comment] 2018-06-12 05:12
Leaving this open until I add some better error messages for this type of thing in AppleCore.

**Comment by squeek502** [comment] 2018-06-12 06:38
Better error messages added in 68dcd8bb357c9a6dabd0c5e4a399d9ba0807df91, RandomTweaks added support in https://github.com/TheRandomLabs/RandomTweaks/commit/0489814bc8b4c84925c27dd81610f2ae6965571e

Closing

**Closed as completed by squeek502** 2018-06-12 06:38 UTC
Labels: bug
